# Generated by Django 5.0.1 on 2024-01-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('professional_website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('degree_earned', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('honors_or_awards', models.CharField(blank=True, max_length=255)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=255)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255)),
                ('proficiency', models.CharField(max_length=255)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_name', models.CharField(max_length=255)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('outcomes', models.TextField(blank=True)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvmakerapp.contactinformation')),
            ],
        ),
    ]
